---
bgp:
  ASN: 65083
  redistribute:
  addressFamily:
    ipv4:
      network:
        - 10.76.64.42/32
  peerGroups:
    - name: SPINE-Underlay
      remoteAs: 65082
      ip:
        - 10.76.64.2
      attributes:
        updateSource:
        ebgpMultihop:
        nextHopUnchanged:
        nextHopSelf:
        communityExtended: true
        maxRoutes: 12000
        allowasIn: 3
      af:
        ipv4: true
